  ███╗   ███╗██╗   ██╗███████╗██╗ ██████╗███████╗██████╗  ██████╗ ███████╗ ██████╗██╗  ██╗███╗   ███╗ ██████╗
  ████╗ ████║██║   ██║██╔════╝██║██╔════╝██╔════╝██╔══██╗██╔═══██╗██╔════╝██╔════╝██║  ██║████╗ ████║██╔════╝
  ██╔████╔██║██║   ██║███████╗██║██║     █████╗  ██████╔╝██║   ██║███████╗██║     ███████║██╔████╔██║██║     
  ██║╚██╔╝██║██║   ██║╚════██║██║██║     ██╔══╝  ██╔══██╗██║   ██║╚════██║██║     ██╔══██║██║╚██╔╝██║██║     
  ██║ ╚═╝ ██║╚██████╔╝███████║██║╚██████╗██║     ██║  ██║╚██████╔╝███████║╚██████╗██║  ██║██║ ╚═╝ ██║╚██████╗
  ╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝
Current date and time: Do 14. Aug 12:03:40 CEST 2025
Current folder: /

|CREATE_Log                                                         250814-12_03_55|
|Work directory: /home/a163/GitRepo/musikfrosch_mc                                 |
|Running script: _main_.py                                                         |
|Spotify token                                                 |nam:Musik|typ: user|
  0%|          | 0/7 [00:00<?, ?it/s] 14%|█▍        | 1/7 [00:06<00:36,  6.04s/it] 29%|██▊       | 2/7 [00:12<00:32,  6.58s/it] 43%|████▎     | 3/7 [00:15<00:19,  4.82s/it] 57%|█████▋    | 4/7 [00:17<00:10,  3.63s/it] 71%|███████▏  | 5/7 [01:03<00:37, 19.00s/it] 86%|████████▌ | 6/7 [01:05<00:13, 13.24s/it] 86%|████████▌ | 6/7 [01:26<00:14, 14.45s/it]
Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporärer Fehler bei der Namensauflösung

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x758ba986f5d0>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='backstage.eu', port=443): Max retries exceeded with url: /veranstaltungen/live.html?p=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x758ba986f5d0>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a163/GitRepo/musikfrosch_mc/_main_.py", line 57, in <module>
    cd.scrapSideCompare('FroschData_10fin', 'FroschData_01', URLs)
  File "/home/a163/GitRepo/musikfrosch_mc/class_dictionary.py", line 103, in scrapSideCompare
    newEvents = scrapSide(URLs)
                ^^^^^^^^^^^^^^^
  File "/home/a163/GitRepo/musikfrosch_mc/class_dictionary.py", line 82, in scrapSide
    events += scraper()
              ^^^^^^^^^
  File "/home/a163/GitRepo/musikfrosch_mc/scrapers.py", line 480, in backstage
    r = requests.get(f"{URL}?p={i}")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a163/anaconda3/envs/musikfrosch/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='backstage.eu', port=443): Max retries exceeded with url: /veranstaltungen/live.html?p=2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x758ba986f5d0>: Failed to establish a new connection: [Errno -3] Temporärer Fehler bei der Namensauflösung'))
|CREATE_Log                                                         250814-12_05_25|
|Work directory: /home/a163/GitRepo/musikfrosch_mc                                 |
|Running script: theatron_functions.py                                             |
  0%|          | 0/108 [00:00<?, ?it/s]100%|██████████| 108/108 [00:00<00:00, 147792.77it/s]
  0%|          | 0/108 [00:00<?, ?it/s] 99%|█████████▉| 107/108 [00:00<00:00, 172.21it/s]100%|██████████| 108/108 [00:00<00:00, 173.68it/s]
  0%|          | 0/108 [00:00<?, ?it/s]100%|██████████| 108/108 [00:00<00:00, 1468.82it/s]
|Theatron MusikSommer 25 | MusikFrosch_MUC updated   | rm:    0|add:    0|sta: DONE|
The whole line-up of SommerFest 2025 - Theatron!   Last update:                                        2025/08/14, 12:06:03
